version: 2
services:
  - type: web
    name: wise-fitness-website
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 80
    autoDeploy: true
    branch: main
