services:
  - type: web
    name: wise-fitness-website
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard
    domains:
      - wise-fitness-app.onrender.com
    
    # Auto-deploy on push to main
    autoDeploy: true
    
    # Headers for security and caching
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.html
        name: Cache-Control
        value: public, max-age=3600
    
    # Disk storage for logs
    disk:
      name: logs
      mountPath: /var/log
      sizeGB: 1
