version: 2
services:
  - type: web
    name: wise-fitness-website
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false  # Will be set manually in Render dashboard
    autoDeploy: true
    branch: main
    
# Render deployment configuration for Wise Fitness Website
# 
# Features:
# - Node.js/Express server serving static files
# - Health check endpoint for Render monitoring
# - Environment variable configuration for OpenAI API
# - Auto-deployment from GitHub main branch
# - Free plan configuration
#
# Setup Instructions:
# 1. Push this file to your GitHub repository
# 2. Connect your GitHub repo to Render
# 3. Set OPENAI_API_KEY environment variable in Render dashboard
# 4. Deploy will start automatically
#
# Health Check:
# Render will monitor /api/health endpoint to ensure service is running
# 
# Static Files:
# All files in "FYP Websites/" directory are served as static content
# Main routes: /, /login, /signup, /admin/*, /services, /events, etc.
