// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZmBzUtEqOp3sC7RemrTOQOcDQCk_iEOA',
    appId: '1:838641447649:web:your_web_app_id',
    messagingSenderId: '838641447649',
    projectId: 'fyp-25-s2-09',
    authDomain: 'fyp-25-s2-09.firebaseapp.com',
    storageBucket: 'fyp-25-s2-09.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZmBzUtEqOp3sC7RemrTOQOcDQCk_iEOA',
    appId: '1:838641447649:android:5607a3443012e4946dbda0',
    messagingSenderId: '838641447649',
    projectId: 'fyp-25-s2-09',
    storageBucket: 'fyp-25-s2-09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZmBzUtEqOp3sC7RemrTOQOcDQCk_iEOA',
    appId: '1:838641447649:ios:your_ios_app_id',
    messagingSenderId: '838641447649',
    projectId: 'fyp-25-s2-09',
    storageBucket: 'fyp-25-s2-09.firebasestorage.app',
    iosBundleId: 'com.example.wiseWorkoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZmBzUtEqOp3sC7RemrTOQOcDQCk_iEOA',
    appId: '1:838641447649:macos:your_macos_app_id',
    messagingSenderId: '838641447649',
    projectId: 'fyp-25-s2-09',
    storageBucket: 'fyp-25-s2-09.firebasestorage.app',
    iosBundleId: 'com.example.wiseWorkoutApp',
  );
}
